system:
  claude-desktop:
    displayName: Claude Desktop
    source: https://claude.ai/download
    icon: https://raw.githubusercontent.com/docker/mcp-gateway/main/img/client/claude.svg
    installCheckPaths:
    - /Applications/Claude.app
    - $AppData\Claude\
    paths:
      linux: $HOME/.config/claude/claude_desktop_config.json
      darwin: $HOME/Library/Application Support/Claude/claude_desktop_config.json
      windows: $APPDATA\Claude\claude_desktop_config.json
    yq:
      list: '.mcpServers | to_entries | map(.value + {"name": .key})'
      set: .mcpServers[$NAME] = $JSON
      del: del(.mcpServers[$NAME])
  continue:
    displayName: Continue.dev
    source: https://www.continue.dev/
    icon: https://raw.githubusercontent.com/docker/mcp-gateway/main/img/client/continue.svg
    installCheckPaths:
    - $HOME/.continue
    - $USERPROFILE\.continue
    paths:
      linux: $HOME/.continue/config.yaml
      darwin: $HOME/.continue/config.yaml
      windows: $USERPROFILE\.continue\config.yaml
    yq:
      list: .mcpServers
      set: .mcpServers = (.mcpServers // []) | .mcpServers += [{"name":$NAME}+$JSON]
      del: del(.mcpServers[] | select(.name == $NAME))
  cursor:
    displayName: Cursor
    source: https://www.cursor.com/
    icon: https://raw.githubusercontent.com/docker/mcp-gateway/main/img/client/cursor.svg
    installCheckPaths:
    - /Applications/Cursor.app
    - $AppData/Cursor/
    paths:
      linux: $HOME/.cursor/mcp.json
      darwin: $HOME/.cursor/mcp.json
      windows: $USERPROFILE\.cursor\mcp.json
    yq:
      list: '.mcpServers | to_entries | map(.value + {"name": .key})'
      set: .mcpServers[$NAME] = $JSON
      del: del(.mcpServers[$NAME])
  lmstudio:
    displayName: LM Studio
    source: https://lmstudio.ai/
    icon: https://raw.githubusercontent.com/docker/mcp-gateway/main/img/client/lmstudio.png
    installCheckPaths:
    - $HOME/.lmstudio
    - $USERPROFILE\.lmstudio
    paths:
      linux: $HOME/.lmstudio/mcp.json
      darwin: $HOME/.lmstudio/mcp.json
      windows: $USERPROFILE\.lmstudio\mcp.json
    yq:
      list: '.mcpServers | to_entries | map(.value + {"name": .key})'
      set: .mcpServers[$NAME] = $JSON
      del: del(.mcpServers[$NAME])
  sema4:
    displayName: Sema4.ai Studio
    source: https://sema4.ai/links/docker-mcp-download
    icon: https://raw.githubusercontent.com/docker/mcp-gateway/main/img/client/sema4.png
    installCheckPaths:
    - $HOME/.sema4ai
    - $USERPROFILE\AppData\Local\sema4ai
    paths:
      linux: $HOME/.sema4ai/sema4ai-studio/mcp_servers.json
      darwin: $HOME/.sema4ai/sema4ai-studio/mcp_servers.json
      windows: $USERPROFILE\AppData\Local\sema4ai\sema4ai-studio\mcp_servers.json
    yq:
      list: '.mcpServers | to_entries | map(.value + {"name": .key})'
      set: .mcpServers[$NAME] = $JSON+{"transport":"stdio"}
      del: del(.mcpServers[$NAME])
project:
  cursor:
    displayname: Cursor
    projectfile: .cursor/mcp.json
    icon: https://raw.githubusercontent.com/docker/mcp-gateway/main/img/client/cursor.svg
    yq:
      list: '.mcpServers | to_entries | map(.value + {"name": .key})'
      set: .mcpServers[$NAME] = $JSON
      del: del(.mcpServers[$NAME])
  vscode:
    displayname: VSCode
    projectfile: .vscode/mcp.json
    icon: https://raw.githubusercontent.com/docker/mcp-gateway/main/img/client/vscode.svg
    yq:
      list: '.servers | to_entries | map(.value + {"name": .key})'
      set: .servers[$NAME] = $JSON+{"type":"stdio"}
      del: del(.servers[$NAME])
