services:
  client:
    build: .
    image: mcp_client
    depends_on:
      - gateway

  gateway:
    image: docker/agents_gateway:v2
    ports:
      - "8811:8811"
    command:
      - --transport=streaming
      - --servers=duckduckgo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
