services:
  client:
    build: .
    environment:
      - MCP_HOST=http://gateway:9011/mcp
    depends_on:
      - gateway

  gateway:
    build:
      dockerfile_inline: |
        FROM docker/agents_gateway:v2
        RUN apk add jq
    command:
      - --transport=streaming
      - --servers=duckduckgo
      - --verbose=false
      - --port=9011
      - --interceptor
      - 'before:exec:echo ============BEFORE==============: Query=$(jq -r ".params.arguments.query") >&2'
      - --interceptor
      - 'before:exec:echo ============AFTER============-==: Done >&2'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
