services:
  gateway:
    image: docker/agents_gateway:v2
    ports:
      - "8811:8811"
    command:
      - --servers=github-official
    # - --secrets=/.env
    # - --config=/.config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - .env:/.env
      # - ~/.docker/mcp/config.yaml:/.config.yaml
