services:
  gateway:
    image: docker/agents_gateway:v2
    ports:
      - "8811:8811"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/run/host-services/backend.sock:/run/host-services/backend.sock"
      - "/var/run/docker.sock.raw:/var/run/docker.sock.raw"
      - "~/.docker/mcp:/mcp"
    command:
      - --catalog=/mcp/catalogs/docker-mcp.yaml
      - --config=/mcp/config.yaml
      - --registry=/mcp/registry.yaml