name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        uses: docker/actions/setup@setup/v1
        with:
          app_id: ${{ secrets.HUB_PLATFORM_APP_ID }}
          app_private_key: ${{ secrets.HUB_PLATFORM_APP_PRIVATE_KEY }}

      - name: Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERBUILDBOT_USERNAME }}
          password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "mcp/cloud-ai-labs"
          install: true

      - name: Lint
        run: make lint

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        uses: docker/actions/setup@setup/v1
        with:
          app_id: ${{ secrets.HUB_PLATFORM_APP_ID }}
          app_private_key: ${{ secrets.HUB_PLATFORM_APP_PRIVATE_KEY }}

      - name: Unit Tests
        run: make unit-tests

  build-module:
    name: Build module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        uses: docker/actions/setup@setup/v1
        with:
          app_id: ${{ secrets.HUB_PLATFORM_APP_ID }}
          app_private_key: ${{ secrets.HUB_PLATFORM_APP_PRIVATE_KEY }}

      - name: Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERBUILDBOT_USERNAME }}
          password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "mcp/cloud-ai-labs"
          install: true

      - name: Build module
        run: make build-test-image
