name: Release docker-mcp as DD Module
run-name: Release DD Module ${{ inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "main"
      tag:
        description: "Release Tag"
        required: true
        type: string
      changelog:
        description: ""
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup
        id: setup
        uses: docker/actions/setup@setup/v1
        with:
          app_id: ${{ secrets.HUB_PLATFORM_APP_ID }}
          app_private_key: ${{ secrets.HUB_PLATFORM_APP_PRIVATE_KEY }}

      - name: Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERBUILDBOT_USERNAME }}
          password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "mcp/cloud-ai-labs"
          install: true

      - name: Build cross platform binaries
        run: |
          make GIT_TAG=${{ github.event.inputs.tag }} docker-mcp-cross

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/
          if-no-files-found: error
          retention-days: 1

  sign:
    needs: build
    uses: docker/desktop-action-private/.github/workflows/sign.yml@main  # this requires adding the GH repo to https://github.com/docker/infra-terraform/blob/main/infra/aws/default/iam/ci_desktop_signing.tf#L32
    with:
      artifacts-name: dist
      filter-win: windows_*/*
      filter-mac: darwin_*/*
    secrets: inherit

  release:
    needs: sign
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Download signed binaries
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Fix binary permissions after upload/download
        run: chmod +x ./dist/*/*

      - name: package binaries in tgz files
        run: |
          make mcp-package

      - name: Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERBUILDBOT_USERNAME }}
          password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "mcp/cloud-ai-labs"
          install: true

      - name: package Docker image and push to hub
        run: |
          make TAG=${{ github.event.inputs.tag }} push-module-image

      - name: Create release with artifacts
        if: ${{ github.event.inputs.tag != '' }} # don't release if no tag is specified
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/*.tar.gz"
          prerelease: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          commit: ${{ github.event.inputs.branch }}

